import {ReactNode} from "react";
import type {Metadata} from "next";
import {ThemeProvider} from "@mui/material";
import CssBaseline from '@mui/material/CssBaseline';
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import InitColorSchemeScript from "@mui/system/InitColorSchemeScript";
import {Provider} from "jotai";

import theme from '../theme';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <InitColorSchemeScript attribute="class" />
        <AppRouterCacheProvider>
            <Provider>
            <ThemeProvider theme={theme}>
                <CssBaseline />
                <div className="App">
                    {children}
                </div>
            </ThemeProvider>
            </Provider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
